package com.riramzy.biomedtrack.domain.model

enum class Department {
    BURN_UNIT,
    CARDIAC_CARE_UNIT,
    CENTRAL_STERILIZATION_UNIT,
    DENTAL_DEPARTMENT,
    DENTAL_PROSTHETICS_LAB,
    DIABETIC_FOOT_UNIT,
    DIALYSIS_UNIT,
    ECHOCARDIOGRAPHY_UNIT,
    EMERGENCY_ROOM,
    INTENSIVE_CARE_UNIT_A,
    INTENSIVE_CARE_UNIT_B,
    LABORATORY,
    NEONATAL_INTENSIVE_CARE_UNIT,
    OBSTETRICS_DEPARTMENT,
    OPERATING_ROOM,
    OUTPATIENT_CLINICS,
    PEDIATRIC_INTENSIVE_CARE_UNIT,
    PEDIATRICS_UNIT,
    PHYSIOTHERAPY_DEPARTMENT,
    RADIOLOGY_DEPARTMENT,
    RECEPTION,
    SURGERY_DEPARTMENT
}

enum class EquipmentStatus {
    ONLINE,
    DUE_SERVICE,
    DOWN
}

enum class UserRole {
    ADMIN,
    TECHNICIAN,
    SUPERVISOR
}

enum class MaintenanceType {
    ROUTINE,
    REPAIR,
    INSPECTION,
    CALIBRATION,
    PREVENTIVE,
    CORRECTIVE,
    EXTERNAL
}

enum class TaskStatus {
    PENDING,
    IN_PROGRESS,
    DONE
}